name: Build App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build: apk
          - os: windows-latest
            build: windows
          - os: macos-latest
            build: macos

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.1
          cache: true
      - run: flutter --version


      - name: Get dependencies
        run: flutter pub get

      - name: Generate lib/const.dart
        run: echo "const SUPABASE_URL = '${{ secrets.SUPABASE_URL }}'; const ANON_KEY = '${{ secrets.SUPABASE_ANON_KEY }}';" > lib/const.dart

      - name: Generate lib/firebase_options.dart
        run: echo "${{ secrets.FIREBASE_OPTIONS_BASE64 }}" | base64 -d > lib/firebase_options.dart

      - name: Build app
        run: flutter build ${{ matrix.build }} --debug
