name: Build App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build: apk
          - os: windows-latest
            build: windows
          - os: macos-latest
            build: macos


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache of dart pub get dependencies
          pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
      - run: flutter --version


      - name: Get dependencies
        run: flutter pub get

      - name: Generate lib/const.dart
        run: echo "const SUPABASE_URL = '${{ secrets.SUPABASE_URL }}'; const ANON_KEY = '${{ secrets.SUPABASE_ANON_KEY }}';" > lib/const.dart

      - name: Generate lib/firebase_options.dart
        run: echo "${{ secrets.FIREBASE_OPTIONS_BASE64 }}" | base64 -d > lib/firebase_options.dart

      - name: Generate google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d > android/app/google-services.json


      - name: Check required files
        run: test -f lib/const.dart && echo "const.dart OK" && test -f lib/firebase_options.dart && echo "firebase_options.dart OK" && test -f android/app/google-services.json && echo "google-services.json OK"

      - name: Generate splash screen
        run: dart run flutter_native_splash:create

      - name: Generate launcher icons
        run: flutter pub run flutter_launcher_icons

      - name: Build app
        run: flutter build ${{ matrix.build }} --debug
